from header_sounds import *


sounds = [
 ("click", sf_2d|sf_vol_3,["drum_3.ogg"]),
 ("tutorial_1", sf_2d|sf_vol_7,["tutorial_1.ogg"]),
 ("tutorial_2", sf_2d|sf_vol_7,["tutorial_2.ogg"]),
 ("gong", sf_2d|sf_priority_9|sf_vol_7, ["s_cymbals.ogg"]),
 ("quest_taken", sf_2d|sf_priority_9|sf_vol_7, []),
 ("quest_completed", sf_2d|sf_priority_9|sf_vol_8, ["quest_completed.ogg"]),
 ("quest_succeeded", sf_2d|sf_priority_9|sf_vol_6, ["quest_succeeded.ogg"]),
 ("quest_concluded", sf_2d|sf_priority_9|sf_vol_7, ["quest_concluded.ogg"]),
 ("quest_failed", sf_2d|sf_priority_9|sf_vol_7, ["quest_failed.ogg"]),
 ("quest_cancelled", sf_2d|sf_priority_9|sf_vol_7, ["quest_cancelled.ogg"]),
 ("rain",sf_2d|sf_priority_10|sf_vol_4|sf_looping, ["rain_1.ogg"]),
 ("money_received",sf_2d|sf_priority_10|sf_vol_4, ["coins_dropped_1.ogg"]),
 ("money_paid",sf_2d|sf_priority_10|sf_vol_10, ["coins_dropped_2.ogg"]),
 ("sword_clash_1", sf_priority_5|sf_vol_8,["sword_clank_metal_09.ogg","sword_clank_metal_09b.ogg","sword_clank_metal_10.ogg","sword_clank_metal_10b.ogg","sword_clank_metal_12.ogg","sword_clank_metal_12b.ogg","sword_clank_metal_13.ogg","sword_clank_metal_13b.ogg"]),
 ("sword_clash_2", sf_priority_5|sf_vol_9,["s_swordClash2.wav"]),
 ("sword_clash_3", sf_priority_5|sf_vol_9,["s_swordClash3.wav"]),
 ("sword_swing", sf_vol_8|sf_priority_2,["weapon_swing_01.ogg","weapon_swing_02.ogg","weapon_swing_03.ogg","weapon_swing_04.ogg","weapon_swing_05.ogg"]),
 ("footstep_grass", sf_vol_4|sf_priority_1,["footstep_1.ogg","footstep_2.ogg","footstep_3.ogg","footstep_4.ogg"]),
 ("footstep_wood", sf_vol_5|sf_priority_1,["footstep_wood_1.ogg","footstep_wood_2.ogg","footstep_wood_4.ogg"]),
 ("footstep_water", sf_vol_4|sf_priority_3,["water_walk_1.ogg","water_walk_2.ogg","water_walk_3.ogg","water_walk_4.ogg"]),
 ("footstep_horse",sf_priority_3|sf_vol_8, ["footstep_horse_5.ogg","footstep_horse_2.ogg","footstep_horse_3.ogg","footstep_horse_4.ogg"]),
 ("footstep_horse_1b",sf_priority_3|sf_vol_8, ["s_footstep_horse_4b.wav","s_footstep_horse_4f.wav","s_footstep_horse_5b.wav","s_footstep_horse_5f.wav"]),
 ("footstep_horse_1f",sf_priority_3|sf_vol_8, ["s_footstep_horse_2b.wav","s_footstep_horse_2f.wav","s_footstep_horse_3b.wav","s_footstep_horse_3f.wav"]),
 ("footstep_horse_2b",sf_priority_3|sf_vol_8, ["s_footstep_horse_2b.wav"]),
 ("footstep_horse_2f",sf_priority_3|sf_vol_8, ["s_footstep_horse_2f.wav"]),
 ("footstep_horse_3b",sf_priority_3|sf_vol_8, ["s_footstep_horse_3b.wav"]),
 ("footstep_horse_3f",sf_priority_3|sf_vol_8, ["s_footstep_horse_3f.wav"]),
 ("footstep_horse_4b",sf_priority_3|sf_vol_8, ["s_footstep_horse_4b.wav"]),
 ("footstep_horse_4f",sf_priority_3|sf_vol_8, ["s_footstep_horse_4f.wav"]),
 ("footstep_horse_5b",sf_priority_3|sf_vol_8, ["s_footstep_horse_5b.wav"]),
 ("footstep_horse_5f",sf_priority_3|sf_vol_8, ["s_footstep_horse_5f.wav"]),
 ("jump_begin", sf_vol_6|sf_priority_9,["jump_begin.ogg"]),
 ("jump_end", sf_vol_5|sf_priority_9,["jump_end.ogg"]),
 ("jump_begin_water", sf_vol_3|sf_priority_9,["jump_begin_water.ogg"]),
 ("jump_end_water", sf_vol_3|sf_priority_9,["jump_end_water.ogg"]),
 ("horse_jump_begin", sf_vol_6|sf_priority_9,["horse_jump_begin.ogg"]),
 ("horse_jump_end", sf_vol_7|sf_priority_9,["horse_jump_end.ogg"]),
 ("horse_jump_begin_water", sf_vol_6|sf_priority_9,["jump_begin_water.ogg"]),
 ("horse_jump_end_water", sf_vol_6|sf_priority_9,["jump_end_water.ogg"]),

 ("release_bow",sf_vol_4, ["bow_shoot_01.ogg","bow_shoot_02.ogg","bow_shoot_03.ogg","bow_shoot_04.ogg","bow_shoot_05.ogg","bow_shoot_06.ogg","bow_shoot_07.ogg","bow_shoot_08.ogg","bow_shoot_09.ogg","bow_shoot_10.ogg"]),
 ("release_crossbow",sf_vol_7, ["crossbow_shoot_01.ogg","crossbow_shoot_02.ogg","crossbow_shoot_03.ogg","crossbow_shoot_04.ogg","crossbow_shoot_05.ogg","crossbow_shoot_06.ogg"]),
 ("throw_javelin",sf_vol_5, ["throw_javelin_2.ogg"]),
 ("throw_axe",sf_vol_7, ["throw_axe_1.ogg"]),
 ("throw_knife",sf_vol_5, ["throw_knife_1.ogg"]),
 ("throw_stone",sf_vol_7, ["throw_stone_1.ogg"]),

 ("reload_crossbow",sf_vol_3, ["pull_crossbow_string_01.ogg","pull_crossbow_string_02.ogg","pull_crossbow_string_03.ogg","pull_crossbow_string_04.ogg","pull_crossbow_string_05.ogg"]),
 ("reload_crossbow_continue",sf_vol_6, ["put_back_dagger.ogg"]),
 ("pull_bow",sf_vol_6, ["pull_bow_string_01.ogg","pull_bow_string_02.ogg","pull_bow_string_03.ogg","pull_bow_string_04.ogg","pull_bow_string_05.ogg"]),
 ("pull_arrow",sf_vol_5, ["draw_arrow_01.ogg","draw_arrow_02.ogg","draw_arrow_03.ogg"]),

 ("arrow_pass_by",sf_priority_7, ["arrow_pass_01.ogg","arrow_pass_02.ogg","arrow_pass_03.ogg","arrow_pass_04.ogg","arrow_pass_05.ogg","arrow_pass_06.ogg","arrow_pass_07.ogg","arrow_pass_08.ogg","arrow_pass_09.ogg","arrow_pass_10.ogg"]),
 ("bolt_pass_by",sf_priority_7, ["bolt_pass_01.ogg","bolt_pass_02.ogg","bolt_pass_03.ogg","bolt_pass_04.ogg","bolt_pass_05.ogg","bolt_pass_06.ogg","bolt_pass_07.ogg","bolt_pass_08.ogg"]),

 ("javelin_pass_by",sf_priority_7, ["javelin_pass_by_1.ogg","javelin_pass_by_2.ogg"]),
 ("stone_pass_by",sf_vol_9|sf_priority_7, ["stone_pass_by_1.ogg"]),
 ("axe_pass_by",sf_priority_7, ["axe_pass_by_1.ogg"]),
 ("knife_pass_by",sf_priority_7, ["knife_pass_by_1.ogg"]),
 ("bullet_pass_by",sf_priority_7, ["bullet_pass_01.ogg","bullet_pass_02.ogg","bullet_pass_03.ogg","bullet_pass_04.ogg"
                                   ,"bullet_pass_05.ogg","bullet_pass_06.ogg","bullet_pass_07.ogg","bullet_pass_08.ogg"
                                   ,"bullet_pass_09.ogg","bullet_pass_10.ogg","bullet_pass_11.ogg","bullet_pass_12.ogg"]),
 
 ("incoming_arrow_hit_ground",sf_priority_7|sf_vol_7, ["arrow_ground_01.ogg","arrow_ground_02.ogg","arrow_ground_03.ogg","arrow_ground_04.ogg","arrow_ground_05.ogg","arrow_ground_06.ogg","arrow_ground_07.ogg","arrow_ground_08.ogg"]),
 ("incoming_bolt_hit_ground",sf_priority_7|sf_vol_7, ["bolt_ground_01.ogg","bolt_ground_02.ogg","bolt_ground_03.ogg","bolt_ground_04.ogg","bolt_ground_05.ogg","bolt_ground_06.ogg","bolt_ground_07.ogg","bolt_ground_08.ogg"]),
 ("incoming_javelin_hit_ground",sf_priority_7|sf_vol_7, ["javelin_ground_01.ogg","javelin_ground_02.ogg","javelin_ground_03.ogg"]),
 ("incoming_stone_hit_ground",sf_priority_7|sf_vol_7, ["stone_ground_01.ogg","stone_ground_02.ogg","stone_ground_03.ogg"]),
 ("incoming_axe_hit_ground",sf_priority_7|sf_vol_7, ["axe_ground_01.ogg","axe_ground_02.ogg","axe_ground_03.ogg"]),
 ("incoming_knife_hit_ground",sf_priority_7|sf_vol_7, ["knife_ground_01.ogg","knife_ground_02.ogg","knife_ground_03.ogg"]),
 ("incoming_bullet_hit_ground",sf_priority_7|sf_vol_7, ["bullet_ric_01.ogg","bullet_ric_02.ogg","bullet_ric_03.ogg"
                                                        ,"bullet_ric_04.ogg","bullet_ric_05.ogg","bullet_ric_06.ogg"
                                                        ,"bullet_ric_07.ogg","bullet_ric_08.ogg"]),

 ("outgoing_arrow_hit_ground",sf_priority_7|sf_vol_7, ["arrow_ground_01.ogg","arrow_ground_02.ogg","arrow_ground_03.ogg","arrow_ground_04.ogg","arrow_ground_05.ogg","arrow_ground_06.ogg","arrow_ground_07.ogg","arrow_ground_08.ogg"]),
 ("outgoing_bolt_hit_ground",sf_priority_7|sf_vol_7,  ["bolt_ground_01.ogg","bolt_ground_02.ogg","bolt_ground_03.ogg","bolt_ground_04.ogg","bolt_ground_05.ogg","bolt_ground_06.ogg","bolt_ground_07.ogg","bolt_ground_08.ogg"]),
 ("outgoing_javelin_hit_ground",sf_priority_7|sf_vol_7, ["javelin_ground_01.ogg","javelin_ground_02.ogg","javelin_ground_03.ogg"]),
 ("outgoing_stone_hit_ground",sf_priority_7|sf_vol_7, ["stone_ground_01.ogg","stone_ground_02.ogg","stone_ground_03.ogg"]),
 ("outgoing_axe_hit_ground",sf_priority_7|sf_vol_7, ["axe_ground_01.ogg","axe_ground_02.ogg","axe_ground_03.ogg"]),
 ("outgoing_knife_hit_ground",sf_priority_7|sf_vol_7, ["knife_ground_01.ogg","knife_ground_02.ogg","knife_ground_03.ogg"]),
 ("outgoing_bullet_hit_ground",sf_priority_7|sf_vol_7, ["bullet_ric_01.ogg","bullet_ric_02.ogg","bullet_ric_03.ogg"
                                                        ,"bullet_ric_04.ogg","bullet_ric_05.ogg","bullet_ric_06.ogg"
                                                        ,"bullet_ric_07.ogg","bullet_ric_08.ogg"]),

 ("draw_sword",sf_priority_2|sf_vol_4, ["draw_sword_02.ogg","draw_sword_03.ogg"]),
 ("put_back_sword",sf_priority_2|sf_vol_4, ["put_away_sword_01.ogg"]),
 ("draw_greatsword",sf_priority_2|sf_vol_4, ["draw_greatsword_01.ogg","draw_greatsword_03.ogg"]),
 ("put_back_greatsword",sf_priority_2|sf_vol_4, ["put_away_greatsword_01.ogg"]),
 ("draw_axe",sf_priority_2|sf_vol_4, ["draw_axe_01.ogg","draw_axe_02.ogg"]),
 ("put_back_axe",sf_priority_2|sf_vol_4, ["put_back_to_holster.ogg"]),
 ("draw_greataxe",sf_priority_2|sf_vol_4, ["draw_spear_01.ogg","draw_spear_02.ogg"]),
 ("put_back_greataxe",sf_priority_2|sf_vol_4, ["put_away_spear_01.ogg"]),
 ("draw_spear",sf_priority_2|sf_vol_4, ["draw_spear_01.ogg","draw_spear_02.ogg"]),
 ("put_back_spear",sf_priority_2|sf_vol_4, ["put_away_spear_01.ogg"]),
 ("draw_crossbow",sf_priority_2|sf_vol_4, ["draw_crossbow_01.ogg","draw_crossbow_02.ogg"]),
 ("put_back_crossbow",sf_priority_2|sf_vol_4, ["put_away_crossbow_01.ogg"]),
 ("draw_revolver",sf_priority_2|sf_vol_4, ["draw_from_holster.ogg"]),
 ("put_back_revolver",sf_priority_2|sf_vol_4, ["put_back_to_holster.ogg"]),
 ("draw_dagger",sf_priority_2|sf_vol_4, ["draw_dagger_01.ogg","draw_dagger_02.ogg"]),
 ("put_back_dagger",sf_priority_2|sf_vol_4, ["put_away_dagger_01.ogg"]),
 ("draw_bow",sf_priority_2|sf_vol_4, ["draw_bow_01.ogg","draw_bow_02.ogg"]),
 ("put_back_bow",sf_priority_2|sf_vol_4, ["put_away_bow_01.ogg"]),
 ("draw_shield",sf_priority_2|sf_vol_4, ["draw_shield_01.ogg","draw_shield_02.ogg"]),
 ("put_back_shield",sf_priority_2|sf_vol_4, ["put_away_shield_01.ogg"]),
 ("draw_other",sf_priority_2|sf_vol_4, ["draw_other.ogg"]),
 ("put_back_other",sf_priority_2|sf_vol_4, ["draw_other2.ogg"]),

 ("body_fall_small",sf_priority_5|sf_vol_9, ["body_fall_small_1.ogg","body_fall_small_2.ogg"]),
 ("body_fall_big",sf_priority_6|sf_vol_8, ["body_fall_1.ogg","body_fall_2.ogg","body_fall_3.ogg"]),
# ("body_fall_very_big",sf_priority_9|sf_vol_10, ["body_fall_very_big_1.ogg"]),
 ("horse_body_fall_begin",sf_priority_6|sf_vol_10, ["horse_body_fall_begin_1.ogg"]),
 ("horse_body_fall_end",sf_priority_6|sf_vol_10, ["horse_body_fall_end_1.ogg","body_fall_2.ogg","body_fall_very_big_1.ogg"]),
 
## ("clang_metal",sf_priority_9, ["clang_metal_1.ogg","clang_metal_2.ogg","s_swordClash1.wav","s_swordClash2.wav","s_swordClash3.wav"]),

 ("hit_wood_wood",sf_priority_7|sf_vol_8, ["wood_on_wood_01.ogg","wood_on_wood_02.ogg","wood_on_wood_03.ogg","wood_on_wood_04.ogg","wood_on_wood_05.ogg","wood_on_wood_06.ogg","wood_on_wood_07.ogg","wood_on_wood_08.ogg"]),#dummy
 ("hit_metal_metal",sf_priority_7|sf_vol_8, ["Sword_clash_01.ogg","Sword_clash_02.ogg","Sword_clash_03.ogg","Sword_clash_04.ogg","Sword_clash_05.ogg","Sword_clash_06.ogg","Sword_clash_07.ogg","Sword_clash_08.ogg","Sword_clash_09.ogg","Sword_clash_10.ogg","Sword_clash_11.ogg","Sword_clash_12.ogg","Sword_clash_13.ogg","Sword_clash_14.ogg","Sword_clash_15.ogg","Sword_clash_16.ogg","Sword_clash_17.ogg","Sword_clash_18.ogg","Sword_clash_19.ogg","Sword_clash_20.ogg","Sword_clash_21.ogg","Sword_clash_22.ogg","Sword_clash_23.ogg","Sword_clash_24.ogg","Sword_clash_25.ogg","Sword_clash_26.ogg","Sword_clash_27.ogg"]),
 ("hit_wood_metal",sf_priority_7|sf_vol_8, ["metal_on_wood_01.ogg","metal_on_wood_02.ogg","metal_on_wood_03.ogg","metal_on_wood_04.ogg","metal_on_wood_05.ogg","metal_on_wood_06.ogg","metal_on_wood_07.ogg","metal_on_wood_08.ogg","metal_on_wood_09.ogg","metal_on_wood_10.ogg"]),
 ("shield_hit_wood_wood",sf_priority_7|sf_vol_7, ["shield_wood_wood_01.ogg","shield_wood_wood_02.ogg","shield_wood_wood_03.ogg","shield_wood_wood_04.ogg","shield_wood_wood_05.ogg","shield_wood_wood_06.ogg","shield_wood_wood_07.ogg","shield_wood_wood_08.ogg","shield_wood_wood_09.ogg","shield_wood_wood_10.ogg","shield_wood_wood_11.ogg","shield_wood_wood_12.ogg"]),
 ("shield_hit_metal_metal",sf_priority_7|sf_vol_8, ["shield_metal_metal_01.ogg","shield_metal_metal_02.ogg","shield_metal_metal_03.ogg","shield_metal_metal_04.ogg","shield_metal_metal_05.ogg","shield_metal_metal_06.ogg","shield_metal_metal_07.ogg","shield_metal_metal_08.ogg","shield_metal_metal_09.ogg","shield_metal_metal_10.ogg","shield_metal_metal_11.ogg","shield_metal_metal_12.ogg"]),
 ("shield_hit_wood_metal",sf_priority_7|sf_vol_8, ["shield_metal_wood_01.ogg","shield_metal_wood_02.ogg","shield_metal_wood_03.ogg","shield_metal_wood_04.ogg","shield_metal_wood_05.ogg","shield_metal_wood_06.ogg","shield_metal_wood_07.ogg","shield_metal_wood_08.ogg","shield_metal_wood_09.ogg","shield_metal_wood_10.ogg"]), #(shield is wood)
 ("shield_hit_metal_wood",sf_priority_7|sf_vol_8, ["shield_wood_metal_01.ogg","shield_wood_metal_02.ogg","shield_wood_metal_03.ogg","shield_wood_metal_04.ogg","shield_wood_metal_05.ogg","shield_wood_metal_06.ogg","shield_wood_metal_07.ogg","shield_wood_metal_08.ogg"]),#(shield is metal)
 ("shield_broken",sf_priority_7|sf_vol_8, ["shield_break_01.ogg","shield_break_02.ogg"]),

 ("man_hit",sf_priority_7|sf_vol_7, ["man_hit_5.ogg","man_hit_6.ogg","man_hit_7.ogg","man_hit_8.ogg","man_hit_9.ogg","man_hit_10.ogg","man_hit_11.ogg","man_hit_12.ogg","man_hit_13.ogg","man_hit_14.ogg","man_hit_15.ogg",
                                      "man_hit_17.ogg","man_hit_18.ogg","man_hit_19.ogg","man_hit_22.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg","man_hit_59.ogg"]),
 ("man_die",sf_priority_10|sf_vol_10,  ["man_die_01.ogg","man_die_02.ogg","man_die_03.ogg",
                                        "man_die_04.ogg","man_die_05.ogg","man_die_06.ogg",
                                        "man_die_07.ogg","man_die_08.ogg","man_die_09.ogg",
                                        "man_die_10.ogg","man_die_11.ogg","man_die_12.ogg","man_die_13.ogg",
                                        "man_die_14.ogg","man_die_15.ogg","man_die_16.ogg","man_die_17.ogg",
                                        "man_die_18.ogg","man_die_19.ogg","man_die_20.ogg","man_die_21.ogg",
                                        "man_die_22.ogg","man_die_23.ogg","man_die_24.ogg","man_die_25.ogg",
                                        "man_die_26.ogg","man_die_27.ogg","man_die_28.ogg","man_die_29.ogg",
                                        "man_die_30.ogg","man_die_31.ogg","man_die_32.ogg"]),
 #("man_die",sf_priority_10|sf_vol_8,  ["man_death_1.ogg","man_death_8.ogg","man_death_8b.ogg","man_death_11.ogg","man_death_14.ogg","man_death_16.ogg","man_death_18.ogg","man_death_21.ogg","man_death_29.ogg","man_death_40.ogg","man_death_44.ogg","man_death_46.ogg","man_death_48.ogg","man_death_64.ogg"]),# ["man_fall_1.ogg","man_fall_2.ogg","man_fall_3.ogg","man_fall_4.ogg"]),
 ("woman_hit",sf_priority_7, ["woman_hit_2.ogg","woman_hit_3.ogg",
                              "woman_hit_b_2.ogg","woman_hit_b_4.ogg","woman_hit_b_6.ogg","woman_hit_b_7.ogg","woman_hit_b_8.ogg",
                              "woman_hit_b_11.ogg","woman_hit_b_14.ogg","woman_hit_b_16.ogg"]),
 ("woman_die",sf_priority_10|sf_vol_9, ["woman_fall_1.ogg","woman_hit_b_5.ogg"]),
 ("woman_yell",sf_priority_8|sf_vol_9, ["woman_yell_1.ogg","woman_yell_2.ogg"]),
 ("hide",0, ["s_hide.wav"]),
 ("unhide",0, ["s_unhide.wav"]),
 ("neigh",0, ["horse_exterior_whinny_01.ogg","horse_exterior_whinny_02.ogg","horse_exterior_whinny_03.ogg","horse_exterior_whinny_04.ogg","horse_exterior_whinny_05.ogg","horse_whinny.ogg"]),
 ("gallop",sf_vol_4, ["horse_gallop_3.ogg","horse_gallop_4.ogg","horse_gallop_5.ogg"]),
 ("battle",sf_vol_4, ["battle.ogg"]),

 ("arrow_hit_body",sf_priority_7, ["missile_flesh_01.ogg","missile_flesh_02.ogg","missile_flesh_03.ogg","missile_flesh_04.ogg","missile_flesh_05.ogg","missile_flesh_06.ogg","missile_flesh_07.ogg","missile_flesh_08.ogg"]),

 ("metal_hit_low_armor_low_damage",sf_priority_5|sf_vol_7, ["metal_low_low_01.ogg","metal_low_low_02.ogg","metal_low_low_03.ogg","metal_low_low_04.ogg","metal_low_low_05.ogg","metal_low_low_06.ogg","metal_low_low_07.ogg","metal_low_low_08.ogg"]),
 ("metal_hit_low_armor_high_damage",sf_priority_5|sf_vol_7, ["metal_low_high_01.ogg","metal_low_high_02.ogg","metal_low_high_03.ogg","metal_low_high_04.ogg","metal_low_high_05.ogg","metal_low_high_06.ogg","metal_low_high_07.ogg","metal_low_high_08.ogg","metal_low_high_09.ogg","metal_low_high_10.ogg","metal_low_high_11.ogg","metal_low_high_12.ogg","metal_low_high_13.ogg","metal_low_high_14.ogg","metal_low_high_15.ogg","metal_low_high_16.ogg","metal_low_high_17.ogg","metal_low_high_18.ogg","metal_low_high_19.ogg","metal_low_high_20.ogg","metal_low_high_21.ogg","metal_low_high_22.ogg","metal_low_high_23.ogg","metal_low_high_24.ogg","metal_low_high_25.ogg","metal_low_high_26.ogg","metal_low_high_27.ogg"]),
 ("metal_hit_high_armor_low_damage",sf_priority_5|sf_vol_7, ["metal_high_low_01.ogg","metal_high_low_02.ogg","metal_high_low_03.ogg","metal_high_low_04.ogg","metal_high_low_05.ogg","metal_high_low_06.ogg","metal_high_low_07.ogg","metal_high_low_08.ogg","metal_high_low_09.ogg","metal_high_low_10.ogg","metal_high_low_11.ogg","metal_high_low_12.ogg","metal_high_low_13.ogg","metal_high_low_14.ogg","metal_high_low_15.ogg","metal_high_low_16.ogg","metal_high_low_17.ogg","metal_high_low_18.ogg","metal_high_low_19.ogg","metal_high_low_20.ogg","metal_high_low_21.ogg","metal_high_low_22.ogg","metal_high_low_23.ogg","metal_high_low_24.ogg","metal_high_low_25.ogg"]),
 ("metal_hit_high_armor_high_damage",sf_priority_5|sf_vol_7, ["metal_high_high_01.ogg","metal_high_high_02.ogg","metal_high_high_03.ogg","metal_high_high_04.ogg","metal_high_high_05.ogg","metal_high_high_06.ogg","metal_high_high_07.ogg","metal_high_high_08.ogg","metal_high_high_09.ogg","metal_high_high_10.ogg","metal_high_high_11.ogg","metal_high_high_12.ogg","metal_high_high_13.ogg","metal_high_high_14.ogg","metal_high_high_15.ogg","metal_high_high_16.ogg","metal_high_high_17.ogg","metal_high_high_18.ogg","metal_high_high_19.ogg","metal_high_high_20.ogg","metal_high_high_21.ogg","metal_high_high_22.ogg","metal_high_high_23.ogg","metal_high_high_24.ogg","metal_high_high_25.ogg","metal_high_high_26.ogg","metal_high_high_27.ogg","metal_high_high_28.ogg","metal_high_high_29.ogg","metal_high_high_30.ogg","metal_high_high_31.ogg","metal_high_high_32.ogg"]),
 ("wooden_hit_low_armor_low_damage",sf_priority_5|sf_vol_7, ["blunt_low_low_01.ogg","blunt_low_low_02.ogg","blunt_low_low_03.ogg","blunt_low_low_04.ogg","blunt_low_low_05.ogg","blunt_low_low_06.ogg","blunt_low_low_07.ogg","blunt_low_low_08.ogg","blunt_low_low_09.ogg","blunt_low_low_10.ogg"]),
 ("wooden_hit_low_armor_high_damage",sf_priority_5|sf_vol_7, ["blunt_low_high_01.ogg","blunt_low_high_02.ogg","blunt_low_high_03.ogg","blunt_low_high_04.ogg","blunt_low_high_05.ogg","blunt_low_high_06.ogg","blunt_low_high_07.ogg","blunt_low_high_08.ogg","blunt_low_high_09.ogg","blunt_low_high_10.ogg","blunt_low_high_11.ogg","blunt_low_high_12.ogg","blunt_low_high_13.ogg"]),
 ("wooden_hit_high_armor_low_damage",sf_priority_5|sf_vol_7, ["blunt_high_low_01.ogg","blunt_high_low_02.ogg","blunt_high_low_03.ogg","blunt_high_low_04.ogg","blunt_high_low_05.ogg","blunt_high_low_06.ogg","blunt_high_low_07.ogg","blunt_high_low_08.ogg","blunt_high_low_09.ogg","blunt_high_low_10.ogg"]),
 ("wooden_hit_high_armor_high_damage",sf_priority_5|sf_vol_7, ["blunt_high_high_01.ogg","blunt_high_high_02.ogg","blunt_high_high_03.ogg","blunt_high_high_04.ogg","blunt_high_high_05.ogg","blunt_high_high_06.ogg","blunt_high_high_07.ogg","blunt_high_high_08.ogg","blunt_high_high_09.ogg","blunt_high_high_10.ogg","blunt_high_high_11.ogg","blunt_high_high_12.ogg","blunt_high_high_13.ogg","blunt_high_high_14.ogg","blunt_high_high_15.ogg","blunt_high_high_16.ogg","blunt_high_high_17.ogg","blunt_high_high_18.ogg","blunt_high_high_19.ogg","blunt_high_high_20.ogg","blunt_high_high_21.ogg","blunt_high_high_22.ogg"]),
 ("mp_arrow_hit_target",sf_2d|sf_priority_15|sf_vol_9, ["mp_arrow_hit_target.ogg"]),
 ("blunt_hit",sf_priority_5|sf_vol_7, ["horse_charge_01.ogg","horse_charge_02.ogg","horse_charge_03.ogg","horse_charge_04.ogg","horse_charge_05.ogg","horse_charge_06.ogg","horse_charge_07.ogg","horse_charge_08.ogg"]),
 ("player_hit_by_arrow",sf_priority_10|sf_vol_10, ["player_hit_by_arrow.ogg"]),
 ("bullet_hit_body",sf_priority_7|sf_vol_8, ["player_hit_by_arrow.ogg"]),
 ("player_hit_by_bullet",sf_priority_7|sf_vol_8, ["player_hit_by_arrow.ogg"]),
 ("pistol_shot",sf_priority_10|sf_vol_15, ["fl_pistol.wav"]),
 ("gun_shot",sf_priority_10|sf_vol_15|sf_use_next_for_far, ["boe_gun_shot_close-01.ogg","boe_gun_shot_close-02.ogg","boe_gun_shot_close-03.ogg"
                                        ,"boe_gun_shot_close-04.ogg","boe_gun_shot_close-05.ogg","boe_gun_shot_close-05.ogg"]),
 ("gun_shot_m",sf_priority_10|sf_vol_10|sf_use_next_for_far, ["boe_gun_shot_med-01.ogg","boe_gun_shot_med-02.ogg","boe_gun_shot_med-03.ogg"
                                        ,"boe_gun_shot_med-04.ogg","boe_gun_shot_med-05.ogg","boe_gun_shot_med-05.ogg"]),
 ("gun_shot_f",sf_priority_10|sf_vol_8, ["boe_gun_shot_far-01.ogg","boe_gun_shot_far-02.ogg","boe_gun_shot_far-03.ogg"
                                        ,"boe_gun_shot_far-04.ogg","boe_gun_shot_far-05.ogg","boe_gun_shot_far-05.ogg"]),

 ("cannon_shot",sf_priority_10|sf_vol_10|sf_use_next_for_far, ["boe_cannon_shot_01.ogg","boe_cannon_shot_02.ogg",
                                                               "boe_cannon_shot_03.ogg","boe_cannon_shot_04.ogg","boe_cannon_shot_05.ogg"]),
 ("cannon_shot_m",sf_priority_9|sf_vol_8|sf_use_next_for_far, ["boe_cannon_shot_01.ogg","boe_cannon_shot_02.ogg",
                                                               "boe_cannon_shot_03.ogg","boe_cannon_shot_04.ogg","boe_cannon_shot_05.ogg"]),
 ("cannon_shot_f",sf_priority_9|sf_vol_4, ["boe_cannon_shot_01.ogg","boe_cannon_shot_02.ogg",
                                                               "boe_cannon_shot_03.ogg","boe_cannon_shot_04.ogg","boe_cannon_shot_05.ogg"]),
 ("explosion",sf_priority_10|sf_vol_15|sf_use_next_for_far, ["boe_explosion_1.ogg","boe_explosion_2.ogg"]),
 ("explosion_m",sf_priority_9|sf_vol_10|sf_use_next_for_far, ["fl_explosion_medium.ogg"]),
 ("explosion_f",sf_priority_9|sf_vol_8, ["fl_explosion_far.ogg"]),
 
 ("man_grunt",sf_priority_3|sf_vol_8, ["man_heavy_grunt_01.ogg","man_heavy_grunt_02.ogg","man_heavy_grunt_03.ogg","man_heavy_grunt_04.ogg","man_heavy_grunt_05.ogg","man_heavy_grunt_06.ogg","man_heavy_grunt_07.ogg","man_heavy_grunt_08.ogg","man_heavy_grunt_09.ogg","man_heavy_grunt_10.ogg","man_heavy_grunt_11.ogg","man_heavy_grunt_12.ogg","man_heavy_grunt_13.ogg","man_heavy_grunt_14.ogg","man_heavy_grunt_15.ogg"]),
 ("man_breath_hard",sf_priority_3|sf_vol_8, ["man_heavy_grunt_01.ogg","man_heavy_grunt_02.ogg","man_heavy_grunt_03.ogg","man_heavy_grunt_04.ogg","man_heavy_grunt_05.ogg","man_heavy_grunt_06.ogg","man_heavy_grunt_07.ogg","man_heavy_grunt_08.ogg","man_heavy_grunt_09.ogg","man_heavy_grunt_10.ogg","man_heavy_grunt_11.ogg","man_heavy_grunt_12.ogg","man_heavy_grunt_13.ogg","man_heavy_grunt_14.ogg","man_heavy_grunt_15.ogg"]),
 ("man_stun",sf_priority_3|sf_vol_9, ["man_short_grunt_01.ogg","man_short_grunt_02.ogg"]),
  ("man_grunt_long",sf_priority_3|sf_vol_7, ["man_heavy_grunt_01.ogg","man_heavy_grunt_02.ogg","man_heavy_grunt_03.ogg","man_heavy_grunt_04.ogg",
                                            "man_heavy_grunt_05.ogg","man_heavy_grunt_06.ogg","man_heavy_grunt_07.ogg","man_heavy_grunt_08.ogg",
                                            "man_heavy_grunt_09.ogg","man_heavy_grunt_10.ogg","man_heavy_grunt_11.ogg","man_heavy_grunt_12.ogg",
                                            "man_heavy_grunt_13.ogg","man_heavy_grunt_14.ogg","man_heavy_grunt_15.ogg",
                                            "man_shortyell_11b.ogg","man_yell_b_18.ogg","man_yell_b_21.ogg","man_yell_b_22.ogg",
                                            "man_yell_b_23.ogg","man_yell_c_20.ogg","man_yell_01.ogg","man_yell_02.ogg","man_yell_03.ogg","man_yell_04.ogg",
                                            "man_yell_05.ogg"]),
 ("man_grunt_unique_1",sf_priority_3|sf_vol_8, ["cepot_exercise_1.ogg","cepot_exercise_2.ogg","cepot_exercise_3.ogg","cepot_exercise_4.ogg","cepot_exercise_5.ogg","cepot_exercise_6.ogg","cepot_exercise_7.ogg",
                                                "cepot_exercise_8.ogg","cepot_exercise_9.ogg","cepot_exercise_10.ogg","cepot_exercise_11.ogg"]),

 ("man_yell",sf_priority_3|sf_vol_7, [
                                      "man_yell_b_21.ogg","man_yell_b_22.ogg","man_yell_b_23.ogg",
                                      "man_yell_c_20.ogg","man_yell_01.ogg","man_yell_02.ogg","man_yell_03.ogg","man_yell_04.ogg","man_yell_05.ogg","man_yell_06.ogg","man_yell_07.ogg","man_yell_08.ogg",
                                      "jawa_yell_1.ogg", "jawa_yell_2.ogg", "jawa_yell_3.ogg", "jawa_yell_4.ogg", "jawa_yell_5.ogg", "jawa_yell_6.ogg", "jawa_yell_7.ogg", "jawa_yell_8.ogg"]),
 ("man_yell2",sf_priority_3|sf_vol_7, ["por_9.wav","por_10.wav",
                                      "por_11.wav","por_12.wav","por_13.wav",
                                      "man_yell_09.ogg","man_yell_10.ogg","man_yell_11.ogg",
                                      "man_yell_12.ogg","man_yell_01.ogg","man_yell_02.ogg","man_yell_03.ogg","man_yell_04.ogg","man_yell_05.ogg","man_yell_06.ogg","man_yell_07.ogg","man_yell_08.ogg",
                                      "por_1.wav", "por_2.wav", "por_3.wav", "por_4.wav", "por_5.wav", "por_6.wav", "por_7.wav", "por_8.wav"]),
 ("man_yell3",sf_priority_3|sf_vol_7, ["man_yell_01.ogg","man_yell_02.ogg","man_yell_03.ogg","man_yell_04.ogg","man_yell_05.ogg","man_yell_06.ogg","man_yell_07.ogg","man_yell_08.ogg",
                                      "man_yell_b_21.ogg","man_yell_b_22.ogg","man_yell_b_23.ogg",
                                      "china_1.ogg", "china_2.ogg", "china_3.ogg", "china_4.ogg", "china_5.ogg", "china_6.ogg", "china_7.ogg", "china_8.ogg"]),
 ("man_yell4",sf_priority_3|sf_vol_7, ["man_yell_b_21.ogg","man_yell_b_22.ogg","man_yell_b_23.ogg",
                                      "man_yell_b_21.ogg","man_yell_b_22.ogg","man_yell_b_23.ogg",
                                      "man_yell_01.ogg","man_yell_02.ogg","man_yell_03.ogg","man_yell_04.ogg","man_yell_05.ogg","man_yell_06.ogg","man_yell_07.ogg","man_yell_08.ogg",
                                      "sunda_1.ogg", "sunda_2.ogg", "sunda_3.ogg", "sunda_4.ogg", "sunda_5.ogg", "sunda_6.ogg", "sunda_7.ogg", "sunda_8.ogg", "sunda_9.ogg"]),

 ("man_yell_unique_1",sf_priority_3|sf_vol_7, ["cepot_yell_1.ogg","cepot_yell_2.ogg","cepot_yell_3.ogg",
                                      "cepot_yell_4.ogg","cepot_yell_5.ogg",
                                      "sunda_1.ogg", "sunda_2.ogg", "sunda_3.ogg", "sunda_4.ogg", "sunda_5.ogg", "sunda_6.ogg", "sunda_7.ogg", "sunda_8.ogg", "sunda_9.ogg"]),
 ("man_warcry",sf_priority_5, ["man_insult_2.ogg","man_insult_3.ogg","man_insult_7.ogg","man_insult_9.ogg","man_insult_13.ogg","man_insult_15.ogg","man_insult_16.ogg"]),

 ("encounter_looters",sf_2d|sf_vol_8, ["encounter_river_pirates_5.ogg","encounter_river_pirates_6.ogg","encounter_river_pirates_9.ogg","encounter_river_pirates_10.ogg","encounter_river_pirates_4.ogg"]),

 ("encounter_bandits",sf_2d|sf_vol_8, ["encounter_bandit_2.ogg","encounter_bandit_9.ogg","encounter_bandit_12.ogg","encounter_bandit_13.ogg","encounter_bandit_15.ogg","encounter_bandit_16.ogg","encounter_bandit_10.ogg",]),
 ("encounter_farmers",sf_2d|sf_vol_8, ["encounter_farmer_2.ogg","encounter_farmer_5.ogg","encounter_farmer_7.ogg","encounter_farmer_9.ogg"]),
 ("encounter_sea_raiders",sf_2d|sf_vol_8, ["encounter_sea_raider_5.ogg","encounter_sea_raider_9.ogg","encounter_sea_raider_9b.ogg","encounter_sea_raider_10.ogg"]),
 ("encounter_steppe_bandits",sf_2d|sf_vol_8, ["encounter_steppe_bandit_3.ogg","encounter_steppe_bandit_3b.ogg","encounter_steppe_bandit_8.ogg","encounter_steppe_bandit_10.ogg","encounter_steppe_bandit_12.ogg"]),
 ("encounter_nobleman",sf_2d|sf_vol_8, ["encounter_nobleman_1.ogg"]),
 ("encounter_vaegirs_ally",sf_2d|sf_vol_8, ["encounter_vaegirs_ally.ogg","encounter_vaegirs_ally_2.ogg"]),
 ("encounter_vaegirs_neutral",sf_2d|sf_vol_8, ["encounter_vaegirs_neutral.ogg","encounter_vaegirs_neutral_2.ogg","encounter_vaegirs_neutral_3.ogg","encounter_vaegirs_neutral_4.ogg"]),
 ("encounter_vaegirs_enemy",sf_2d|sf_vol_8, ["encounter_vaegirs_neutral.ogg","encounter_vaegirs_neutral_2.ogg","encounter_vaegirs_neutral_3.ogg","encounter_vaegirs_neutral_4.ogg"]),
 ("sneak_town_halt",sf_2d, ["sneak_halt_1.ogg","sneak_halt_2.ogg"]),
 ("horse_walk",sf_priority_3|sf_vol_5, ["horse_walk_1.ogg","horse_walk_2.ogg","horse_walk_3.ogg","horse_walk_4.ogg"]),
 ("horse_trot",sf_priority_4|sf_vol_6, ["horse_trot_1.ogg","horse_trot_2.ogg","horse_trot_3.ogg","horse_trot_4.ogg"]),
 ("horse_canter",sf_priority_4|sf_vol_7, ["horse_canter_1.ogg","horse_canter_2.ogg","horse_canter_3.ogg","horse_canter_4.ogg"]),
 ("horse_gallop",sf_priority_5|sf_vol_8, ["horse_gallop_6.ogg","horse_gallop_7.ogg","horse_gallop_8.ogg","horse_gallop_9.ogg"]),
 ("horse_breath",sf_priority_1|sf_vol_4, ["horse_breath_4.ogg","horse_breath_5.ogg","horse_breath_6.ogg","horse_breath_7.ogg"]),
 ("horse_snort",sf_priority_1|sf_vol_2, ["horse_snort_1.ogg","horse_snort_2.ogg","horse_snort_3.ogg","horse_snort_4.ogg","horse_snort_5.ogg"]),
 ("horse_low_whinny",sf_vol_12, ["horse_whinny-1.ogg","horse_whinny-2.ogg"]),
 ("block_fist",0, ["block_fist_3.ogg","block_fist_4.ogg"]),
 ("man_hit_blunt_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_blunt_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_pierce_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_pierce_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_cut_weak",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_hit_cut_strong",sf_priority_5|sf_vol_10, ["man_hit_13.ogg","man_hit_29.ogg","man_hit_32.ogg","man_hit_47.ogg","man_hit_57.ogg"]),
 ("man_victory",sf_priority_5|sf_vol_10, ["man_victory_3.ogg","man_victory_4.ogg","man_victory_5.ogg","man_victory_8.ogg","man_victory_15.ogg","man_victory_49.ogg","man_victory_52.ogg","man_victory_54.ogg","man_victory_57.ogg","man_victory_71.ogg"]),
 ("man_victory2",sf_priority_5|sf_vol_10, ["victoria_1.wav","victoria_2.wav","victoria_3.wav","victoria_4.wav","victoria_5.wav","victoria_6.wav","victoria_7.wav","victoria_8.wav","victoria_9.wav","victoria_10.wav","victoria_11.wav","victoria_12.wav","victoria_13.wav","victoria_14.wav"]),

 ("fire_loop",sf_priority_9|sf_vol_7|sf_looping|sf_start_at_random_pos, ["boe_lamp_1.ogg", "boe_lamp_2.ogg", "boe_lamp_3.ogg"]),
 ("torch_loop",sf_priority_9|sf_vol_7|sf_looping|sf_start_at_random_pos, ["boe_torch_1.ogg", "boe_torch_2.ogg", "boe_torch_3.ogg"]),
 ("fire_big_loop",sf_priority_9|sf_vol_10|sf_looping|sf_start_at_random_pos, ["boe_fire_big_1.ogg", "boe_fire_big_2.ogg", "boe_fire_big_3.ogg"]),
 ("fire_med_loop",sf_priority_9|sf_vol_8|sf_looping|sf_start_at_random_pos, ["boe_fire_med_1.ogg", "boe_fire_med_2.ogg", "boe_fire_med_3.ogg"]),
 ("fire_sml_loop",sf_priority_9|sf_vol_7|sf_looping|sf_start_at_random_pos, ["boe_fire_sml_1.ogg", "boe_fire_sml_2.ogg", "boe_fire_sml_3.ogg"]),
 ("dummy_hit",sf_priority_7|sf_vol_6, ["dummy_hit_01.ogg","dummy_hit_02.ogg","dummy_hit_03.ogg"]),
 ("dummy_destroyed",sf_priority_7|sf_vol_6, ["dummy_break_01.ogg","dummy_break_02.ogg","dummy_break_03.ogg","dummy_break_04.ogg","dummy_break_05.ogg"]),
 ("gourd_destroyed",sf_priority_7|sf_vol_6, ["dummy_break_01.ogg","dummy_break_02.ogg","dummy_break_03.ogg","dummy_break_04.ogg","dummy_break_05.ogg"]),#TODO
 ("cow_moo", sf_2d|sf_priority_9|sf_vol_8, ["cow_moo_1.ogg"]),
 ("cow_slaughter", sf_2d|sf_priority_9|sf_vol_8, ["cow_slaughter.ogg"]),
 ("distant_dog_bark", sf_2d|sf_priority_3|sf_vol_8, ["ambient_random_dog_1.wav","ambient_random_dog_2.wav","ambient_random_dog_3.wav","ambient_random_dog_4.wav","ambient_random_dog_5.wav","ambient_random_dog_6.wav"]),
 ("distant_owl", sf_2d|sf_priority_3|sf_vol_9, ["d_owl2.ogg","d_owl3.ogg","d_owl4.ogg"]),
 ("distant_chicken", sf_2d|sf_priority_3|sf_vol_8, ["ambient_random_chicken_1.wav","ambient_random_chicken_2.wav","ambient_random_chicken_3.wav","ambient_random_chicken_4.wav","ambient_random_chicken_5.wav"]),
 ("distant_carpenter", sf_2d|sf_priority_3|sf_vol_3, ["d_carpenter1.ogg","d_saw_short3.ogg"]),
 ("distant_blacksmith", sf_2d|sf_priority_3|sf_vol_4, ["ambient_random_cow_1.wav","ambient_random_cow_2.wav","ambient_random_cow_3.wav","ambient_random_cow_4.wav","ambient_random_cow_5.wav"]),
 ("chicken_cluck", sf_priority_9|sf_vol_9, ["npc_chicken_cluck_01.ogg","npc_chicken_cluck_02.ogg","npc_chicken_cluck_03.ogg"]),
 ("dog_pant", sf_priority_9|sf_vol_9, ["dog_pant.ogg"]),

 ("arena_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["arena_loop11.ogg"]),
 ("town_ambiance", sf_2d|sf_priority_8|sf_vol_3|sf_looping, ["taverna_ambience.ogg"]),
 ("tutorial_fail", sf_2d|sf_vol_7,["cue_failure.ogg"]),
 ("your_flag_taken", sf_2d|sf_priority_10|sf_vol_10, ["your_flag_taken.ogg"]),
 ("enemy_flag_taken", sf_2d|sf_priority_10|sf_vol_10, ["enemy_flag_taken.ogg"]),
 ("flag_returned", sf_2d|sf_priority_10|sf_vol_10, ["your_flag_returned.ogg"]),
 ("team_scored_a_point", sf_2d|sf_priority_10|sf_vol_10, ["you_scored_a_point.ogg"]),
 ("enemy_scored_a_point", sf_2d|sf_priority_10|sf_vol_10, ["enemy_scored_a_point.ogg"]),
 ("watersplash_sml",sf_priority_7|sf_vol_8, ["boe_watersplash_sml_1.ogg", "boe_watersplash_sml_2.ogg"]),
 ("watersplash_med",sf_priority_7|sf_vol_8, ["boe_watersplash_med_1.ogg", "boe_watersplash_med_2.ogg"]),
 ("fire_sml",sf_priority_9|sf_vol_10|sf_looping|sf_start_at_random_pos, ["boe_fire_sml_1.ogg", "boe_fire_sml_2.ogg", "boe_fire_sml_3.ogg"]),
 ("fire_med",sf_priority_9|sf_vol_10|sf_looping|sf_start_at_random_pos, ["boe_fire_med_1.ogg", "boe_fire_med_2.ogg", "boe_fire_med_3.ogg"]),
 ("fire_big",sf_priority_9|sf_vol_12|sf_looping|sf_start_at_random_pos, ["boe_fire_big_1.ogg", "boe_fire_big_2.ogg", "boe_fire_big_3.ogg"]),

 ("mosque_ambiance", sf_priority_10|sf_vol_15|sf_use_next_for_far, ["amb_mosque_1.ogg","amb_mosque_2.ogg","amb_mosque_3.ogg","amb_mosque_4.ogg","amb_mosque_5.ogg","amb_mosque_6.ogg","amb_mosque_athan_a.ogg"]),
 ("mosque_ambiance_f", sf_priority_10|sf_vol_15, ["amb_mosque_1.ogg","amb_mosque_2.ogg","amb_mosque_3.ogg","amb_mosque_4.ogg","amb_mosque_5.ogg","amb_mosque_6.ogg","amb_mosque_athan_a.ogg"]),
 ("mosque_ambiance_fajr", sf_priority_10|sf_vol_15|sf_looping, ["town_loop_3.ogg"]),
 ("mosque_ambiance_athan", sf_priority_10|sf_vol_15|sf_looping, ["town_loop_3.ogg"]),

 ("decapitation",sf_priority_5|sf_vol_7, ["metal_high_high_01.ogg","metal_high_high_02.ogg","metal_high_high_03.ogg","metal_high_high_04.ogg","metal_high_high_05.ogg","metal_high_high_06.ogg","metal_high_high_07.ogg","metal_high_high_08.ogg","metal_high_high_09.ogg","metal_high_high_10.ogg","metal_high_high_11.ogg","metal_high_high_12.ogg","metal_high_high_13.ogg","metal_high_high_14.ogg","metal_high_high_15.ogg","metal_high_high_16.ogg","metal_high_high_17.ogg","metal_high_high_18.ogg","metal_high_high_19.ogg","metal_high_high_20.ogg","metal_high_high_21.ogg","metal_high_high_22.ogg","metal_high_high_23.ogg","metal_high_high_24.ogg","metal_high_high_25.ogg","metal_high_high_26.ogg","metal_high_high_27.ogg","metal_high_high_28.ogg","metal_high_high_29.ogg","metal_high_high_30.ogg","metal_high_high_31.ogg","metal_high_high_32.ogg"]),

 ("ocean_ambiance", sf_priority_5|sf_vol_5|sf_looping|sf_use_next_for_far, ["amb_water_exterior_coast_waves_01_lp.ogg","amb_water_exterior_coast_waves_02_lp.ogg","amb_water_exterior_coast_waves_03_lp.ogg"]),
 ("ocean_ambiance_medium", sf_2d|sf_priority_5|sf_vol_5|sf_looping|sf_use_next_for_far, ["boe_ocean_ambiance.ogg"]),
 ("ocean_ambiance_far", sf_2d|sf_priority_5|sf_vol_5|sf_looping, ["boe_ocean_ambiance_distant.ogg"]),
 ("ocean_gulls_ambiance", sf_priority_10|sf_vol_10|sf_looping, ["boe_ocean_gulls.ogg"]),
 ("ocean_gulls_ambiance_f", sf_priority_8|sf_vol_5|sf_looping|sf_use_next_for_far, ["boe_ocean_gulls.ogg"]),
 ("ocean_waves_1", sf_priority_8|sf_vol_10, ["volni_bereg.ogg"]),
 ("ocean_waves_2", sf_priority_8|sf_vol_10, ["volni_bereg_1.ogg"]),
 ("ocean_waves_3", sf_priority_8|sf_vol_10, ["volni_bereg_2.ogg"]),
 ("ocean_waves_4", sf_priority_8|sf_vol_10, ["volni_bereg_3.ogg"]),
 ("ocean_waves_5", sf_priority_8|sf_vol_10, ["volni_bereg_4.ogg"]),
 ("ocean_waves_6", sf_priority_8|sf_vol_10, ["volni_bereg_5.ogg"]),
 ("ocean_waves_7", sf_priority_8|sf_vol_10, ["volni_bereg_6.ogg"]),
 ("ocean_waves_8", sf_priority_8|sf_vol_10, ["volni_bereg_7.ogg"]),
 ("plain_birds", sf_2d|sf_priority_7|sf_vol_8|sf_looping, ["boe_plain_birds.ogg"]),
 ("plain_ambiance_day", sf_2d|sf_priority_5|sf_vol_8|sf_looping, ["boe_plain_ambiance_day.ogg"]),
 ("river_ambiance", sf_priority_4|sf_vol_3|sf_looping, ["ruchei_1.ogg","ruchei_2.ogg","ruchei_3.ogg","ruchei_4.ogg"]),

 #INVASION MODE START
 ("ccoop_spawn_companion_0",sf_vol_8, ["encounter_farmer_2.ogg"]),
 ("ccoop_spawn_companion_1",sf_vol_8, ["encounter_farmer_5.ogg"]),
 ("ccoop_spawn_companion_2",sf_vol_8, ["encounter_farmer_7.ogg"]),
 ("ccoop_spawn_companion_3",sf_vol_8, ["encounter_farmer_9.ogg"]),
 ("ccoop_nobleman_taunt",sf_vol_8, ["encounter_nobleman_1.ogg"]),
 ("ccoop_looter_taunt_0",sf_vol_8, ["encounter_river_pirates_5.ogg"]),
 ("ccoop_looter_taunt_1",sf_vol_8, ["encounter_river_pirates_6.ogg"]),
 ("ccoop_looter_taunt_2",sf_vol_8, ["encounter_river_pirates_9.ogg"]),
 ("ccoop_looter_taunt_3",sf_vol_8, ["encounter_river_pirates_10.ogg"]),
 ("ccoop_looter_taunt_4",sf_vol_8, ["encounter_river_pirates_4.ogg"]),
 ("ccoop_bandit_taunt_0",sf_vol_8, ["encounter_bandit_2.ogg"]),
 ("ccoop_bandit_taunt_1",sf_vol_8, ["encounter_bandit_9.ogg"]),
 ("ccoop_bandit_taunt_2",sf_vol_8, ["encounter_bandit_12.ogg"]),
 ("ccoop_bandit_taunt_3",sf_vol_8, ["encounter_bandit_13.ogg"]),
 ("ccoop_bandit_taunt_4",sf_vol_8, ["encounter_bandit_15.ogg"]),
 ("ccoop_bandit_taunt_5",sf_vol_8, ["encounter_bandit_16.ogg"]),
 ("ccoop_bandit_taunt_6",sf_vol_8, ["encounter_bandit_10.ogg"]),
 ("ccoop_sea_raider_taunt_0",sf_vol_8, ["encounter_sea_raider_5.ogg"]),
 ("ccoop_sea_raider_taunt_1",sf_vol_8, ["encounter_sea_raider_9.ogg"]),
 ("ccoop_sea_raider_taunt_2",sf_vol_8, ["encounter_sea_raider_9b.ogg"]),
 ("ccoop_sea_raider_taunt_3",sf_vol_8, ["encounter_sea_raider_10.ogg"]),
 ("sounds_end", sf_priority_10|sf_vol_10, ["enemy_scored_a_point.ogg"]),
 #INVASION MODE END
]
# modmerger_start version=201 type=2
try:
    component_name = "sounds"
    var_set = { "sounds" : sounds }
    from modmerger import modmerge
    modmerge(var_set)
except:
    raise
# modmerger_end
